name: build docker-ocr_api_server image

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
      tags:
        description: "Test scenario tags"

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get current date
        id: date
        run: echo "::set-output name=today::$(date +'%Y-%m-%d_%H-%M')"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Modify APT sources
        run: |
          cd docker
          echo "deb http://mirrors.aliyun.com/debian buster main" > sources.list
          echo "deb http://mirrors.aliyun.com/debian buster-updates main" >> sources.list
          echo "deb http://mirrors.aliyun.com/debian-security buster/updates main" >> sources.list

      - name: Clone source code
        run: |
          df -hT $PWD
          git clone https://github.com/OpenListTeam/ocr_api_server.git docker
          cd docker

      - name: Check requirements.txt
        run: |
          cd docker
          cat requirements.txt

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./docker
          file: ./docker/Dockerfile
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            hanshaobo/ocr_api_server:${{ steps.date.outputs.today }}
            hanshaobo/ocr_api_server:latest
          no-cache: true
          progress: plain
